packages:
  branch_codenames:
    master: trusty-unstable
    production: trusty-stable

jobs:
  slackcat:
    builder: "make"
    base: "quay.io/madebymany/build-bases:trusty"
    build_depends:
      - "golang"
    packages:
      - type: debian
        name: slackcat
        repos:
          - composed-public
        target: install
