software_groups: &software
  - "base_trusty"

packages:
  branch_codenames:
    master: unstable
    production: stable

jobs:
  slackcat:
    builder: "make"
    base: "ubuntu:14.04"
    software_groups: *software
    build_depends:
      - "golang"
    promote_through:
      - unstable
      - stable
    packages:
      - name: slackcat
        repos:
          - test
        target: install
